project_id = "cmnwwchipysvwvijqjcu"

[functions.send-contact-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.newsletter-subscription]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false
