"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  Loader2,
  RefreshCcw,
  Link as LinkIcon,
  CircleHelp,
} from "lucide-react";
import Link from "next/link";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { ComboBox, type ComboOption } from "@/components/ui/combobox";
import { useToast } from "@/hooks/use-toast";

type InventoryEntry = {
  routeKey: string;
  pathname: string;
  indexable: boolean;
  sourceType: string;
  label: string;
  locale: "en" | "ar";
  sourceTitle?: string | null;
  sourceDescription?: string | null;
  sourceOgImage?: string | null;
  updatedAt?: string | null;
  needsSeoScore: number;
};

type AutogeneratedSeoState = {
  title: string;
  description: string;
  canonicalUrl: string;
  robotsIndex: boolean;
  robotsFollow: boolean;
  ogTitle: string;
  ogDescription: string;
  ogImageUrl: string;
  twitterTitle: string;
  twitterDescription: string;
  twitterImageUrl: string;
  keywords: string;
  aiSummary: string;
  llmsInclude: boolean;
  llmsPriority: number;
};

type SeoOverride = {
  id: string;
  route_key: string;
  locale: "en" | "ar";
  title: string | null;
  description: string | null;
  canonical_url: string | null;
  robots_index: boolean;
  robots_follow: boolean;
  og_title: string | null;
  og_description: string | null;
  og_image_url: string | null;
  twitter_title: string | null;
  twitter_description: string | null;
  twitter_image_url: string | null;
  keywords: string[] | null;
  ai_summary: string | null;
  llms_include: boolean;
  llms_priority: number;
  updated_at: string;
};

type RouteRedirect = {
  id: string;
  from_path: string;
  to_path: string;
  code: 301 | 302 | 307 | 308;
  is_active: boolean;
  source: string | null;
  updated_at: string;
};

type InventoryResponse = {
  locale: "en" | "ar";
  sourceTypes?: string[];
  summary: {
    total: number;
    highPriority: number;
    mediumPriority: number;
    lowPriority: number;
  };
  entries: InventoryEntry[];
};

type OverrideFormState = {
  routeKey: string;
  locale: "en" | "ar";
  updatedAt: string | null;
  hasExistingOverride: boolean;
  autogenerated: AutogeneratedSeoState;
  title: string;
  description: string;
  canonicalUrl: string;
  robotsIndex: boolean;
  robotsFollow: boolean;
  ogTitle: string;
  ogDescription: string;
  ogImageUrl: string;
  twitterTitle: string;
  twitterDescription: string;
  twitterImageUrl: string;
  keywords: string;
  aiSummary: string;
  llmsInclude: boolean;
  llmsPriority: number;
};

type SeoHealthFilter = "all" | "needs-attention" | "good" | "excellent";
type DraftVisibilityFilter = "all" | "drafts";

type EditorFeedbackState = {
  tone: "success" | "error" | "info";
  message: string;
};

type OverrideDraftSnapshot = Pick<
  OverrideFormState,
  | "title"
  | "description"
  | "canonicalUrl"
  | "robotsIndex"
  | "robotsFollow"
  | "ogTitle"
  | "ogDescription"
  | "ogImageUrl"
  | "twitterTitle"
  | "twitterDescription"
  | "twitterImageUrl"
  | "keywords"
  | "aiSummary"
  | "llmsInclude"
  | "llmsPriority"
>;

type SeoOverrideDraft = OverrideDraftSnapshot & {
  savedAt: string;
};

type WorkspaceDraftNotice = {
  routeKey: string;
  locale: "en" | "ar";
  savedAt: string;
};

const trimToText = (value: string | null | undefined) =>
  typeof value === "string" ? value.trim() : "";

const buildAutogeneratedState = (
  entry: InventoryEntry,
): AutogeneratedSeoState => {
  const title = trimToText(entry.sourceTitle);
  const description = trimToText(entry.sourceDescription);
  const image = trimToText(entry.sourceOgImage);

  return {
    title,
    description,
    canonicalUrl: entry.pathname,
    robotsIndex: true,
    robotsFollow: true,
    ogTitle: title,
    ogDescription: description,
    ogImageUrl: image,
    twitterTitle: title,
    twitterDescription: description,
    twitterImageUrl: image,
    keywords: "",
    aiSummary: description,
    llmsInclude: true,
    llmsPriority: 0,
  };
};

const defaultFormState = (
  routeKey: string,
  locale: "en" | "ar",
  autogenerated: AutogeneratedSeoState,
): OverrideFormState => ({
  routeKey,
  locale,
  updatedAt: null,
  hasExistingOverride: false,
  autogenerated,
  title: "",
  description: "",
  canonicalUrl: "",
  robotsIndex: true,
  robotsFollow: true,
  ogTitle: "",
  ogDescription: "",
  ogImageUrl: "",
  twitterTitle: "",
  twitterDescription: "",
  twitterImageUrl: "",
  keywords: "",
  aiSummary: "",
  llmsInclude: true,
  llmsPriority: 0,
});

const clampLlmsPriority = (value: number) =>
  Math.max(-100, Math.min(100, Math.trunc(value)));

const toEffectiveValue = (
  overrideValue: string,
  autogeneratedValue: string,
) => {
  const override = trimToText(overrideValue);
  if (override.length > 0) {
    return override;
  }

  const autogenerated = trimToText(autogeneratedValue);
  return autogenerated.length > 0 ? autogenerated : null;
};

const formatAutogeneratedValue = (
  value: string | number | boolean | null | undefined,
  fallback = "None",
) => {
  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }
  if (typeof value === "number") {
    return `${value}`;
  }
  if (typeof value === "string") {
    const trimmed = value.trim();
    return trimmed.length > 0 ? trimmed : fallback;
  }

  return fallback;
};

const AUTOGENERATED_VALUE_CLASS =
  "w-full whitespace-normal text-sm text-muted-foreground [overflow-wrap:anywhere]";

const hasTextOverride = (value: string) => trimToText(value).length > 0;

const SEO_DRAFTS_STORAGE_KEY = "cms-seo-override-drafts-v1";

const buildDraftStorageId = (routeKey: string, locale: "en" | "ar") =>
  `${locale}::${routeKey}`;

const toDraftSnapshot = (
  formState: OverrideFormState,
): OverrideDraftSnapshot => ({
  title: formState.title,
  description: formState.description,
  canonicalUrl: formState.canonicalUrl,
  robotsIndex: formState.robotsIndex,
  robotsFollow: formState.robotsFollow,
  ogTitle: formState.ogTitle,
  ogDescription: formState.ogDescription,
  ogImageUrl: formState.ogImageUrl,
  twitterTitle: formState.twitterTitle,
  twitterDescription: formState.twitterDescription,
  twitterImageUrl: formState.twitterImageUrl,
  keywords: formState.keywords,
  aiSummary: formState.aiSummary,
  llmsInclude: formState.llmsInclude,
  llmsPriority: formState.llmsPriority,
});

const applyDraftToFormState = (
  formState: OverrideFormState,
  draft: SeoOverrideDraft,
): OverrideFormState => {
  const { savedAt: _savedAt, ...snapshot } = draft;
  return {
    ...formState,
    ...snapshot,
  };
};

const readSeoOverrideDrafts = (): Record<string, SeoOverrideDraft> => {
  if (typeof window === "undefined") {
    return {};
  }

  try {
    const raw = window.localStorage.getItem(SEO_DRAFTS_STORAGE_KEY);
    if (!raw) {
      return {};
    }

    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object") {
      return {};
    }

    return parsed as Record<string, SeoOverrideDraft>;
  } catch {
    return {};
  }
};

const writeSeoOverrideDrafts = (drafts: Record<string, SeoOverrideDraft>) => {
  if (typeof window === "undefined") {
    return;
  }

  try {
    window.localStorage.setItem(SEO_DRAFTS_STORAGE_KEY, JSON.stringify(drafts));
  } catch {
    // Ignore localStorage failures and keep editing flow uninterrupted.
  }
};

const getSeoHealthBadge = (score: number) => {
  if (score >= 60) {
    return { label: "Needs attention", variant: "destructive" as const };
  }
  if (score >= 30) {
    return { label: "Good", variant: "secondary" as const };
  }

  return { label: "Excellent", variant: "success" as const };
};

const matchesSeoHealthFilter = (score: number, filter: SeoHealthFilter) => {
  if (filter === "needs-attention") {
    return score >= 60;
  }
  if (filter === "good") {
    return score >= 30 && score < 60;
  }
  if (filter === "excellent") {
    return score < 30;
  }

  return true;
};

const formatSourceTypeLabel = (value: string) => {
  if (value === "all") {
    return "All";
  }

  return value
    .split("-")
    .map((part) => (part ? `${part[0]!.toUpperCase()}${part.slice(1)}` : part))
    .join(" ");
};

const formatDraftSavedRelative = (savedAt: string) => {
  const parsed = new Date(savedAt);
  if (Number.isNaN(parsed.getTime())) {
    return "recently";
  }

  const diffSeconds = Math.round((parsed.getTime() - Date.now()) / 1000);
  const absSeconds = Math.abs(diffSeconds);
  const rtf = new Intl.RelativeTimeFormat("en", { numeric: "auto" });

  if (absSeconds < 60) {
    return rtf.format(diffSeconds, "second");
  }
  const diffMinutes = Math.round(diffSeconds / 60);
  if (Math.abs(diffMinutes) < 60) {
    return rtf.format(diffMinutes, "minute");
  }
  const diffHours = Math.round(diffMinutes / 60);
  if (Math.abs(diffHours) < 24) {
    return rtf.format(diffHours, "hour");
  }
  const diffDays = Math.round(diffHours / 24);
  return rtf.format(diffDays, "day");
};

const formatDraftSavedAbsolute = (savedAt: string) => {
  const parsed = new Date(savedAt);
  if (Number.isNaN(parsed.getTime())) {
    return "Unknown time";
  }

  return parsed.toLocaleString();
};

function FieldStatusBadge({ overridden }: { overridden: boolean }) {
  return (
    <Badge
      variant={overridden ? "secondary" : "outline"}
      className="h-5 self-start shrink-0 px-1.5 py-0 text-[11px] font-medium normal-case tracking-normal"
    >
      {overridden ? "Override" : "Auto"}
    </Badge>
  );
}

const normalizeRedirectPathInput = (value: string) => value.trim();

const isValidSitePath = (value: string) => /^\/(?!\/)/.test(value);

async function authedFetch(input: string, init?: RequestInit) {
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session?.access_token) {
    throw new Error("Authentication required");
  }

  const headers = new Headers(init?.headers);
  headers.set("Authorization", `Bearer ${session.access_token}`);

  return fetch(input, {
    ...init,
    headers,
  });
}

export default function CmsSeoWorkspacePage() {
  const { toast } = useToast();
  const [locale, setLocale] = useState<"en" | "ar">("en");
  const [sourceType, setSourceType] = useState<string>("all");
  const [sourceTypeCatalog, setSourceTypeCatalog] = useState<string[]>([]);
  const [seoHealthFilter, setSeoHealthFilter] =
    useState<SeoHealthFilter>("all");
  const [draftVisibilityFilter, setDraftVisibilityFilter] =
    useState<DraftVisibilityFilter>("all");
  const [selectedRouteKey, setSelectedRouteKey] = useState("");
  const [helpDialogOpen, setHelpDialogOpen] = useState(false);
  const [draftsByStorageId, setDraftsByStorageId] = useState<
    Record<string, SeoOverrideDraft>
  >({});
  const [workspaceDraftNotice, setWorkspaceDraftNotice] =
    useState<WorkspaceDraftNotice | null>(null);
  const [queuedPublishStorageId, setQueuedPublishStorageId] = useState<
    string | null
  >(null);
  const editorRequestRef = useRef(0);

  const [editorOpen, setEditorOpen] = useState(false);
  const [editorLoading, setEditorLoading] = useState(false);
  const [editorSaving, setEditorSaving] = useState(false);
  const [editorFeedback, setEditorFeedback] =
    useState<EditorFeedbackState | null>(null);
  const [formState, setFormState] = useState<OverrideFormState | null>(null);

  const [redirectFrom, setRedirectFrom] = useState("");
  const [redirectTo, setRedirectTo] = useState("");
  const [redirectSaving, setRedirectSaving] = useState(false);
  const [redirectToggleId, setRedirectToggleId] = useState<string | null>(null);

  useEffect(() => {
    setDraftsByStorageId(readSeoOverrideDrafts());

    const onStorage = (event: StorageEvent) => {
      if (event.key === SEO_DRAFTS_STORAGE_KEY || event.key === null) {
        setDraftsByStorageId(readSeoOverrideDrafts());
      }
    };

    window.addEventListener("storage", onStorage);
    return () => window.removeEventListener("storage", onStorage);
  }, []);

  const persistDrafts = useCallback(
    (drafts: Record<string, SeoOverrideDraft>) => {
      writeSeoOverrideDrafts(drafts);
      setDraftsByStorageId(drafts);
    },
    [],
  );

  const inventoryQuery = useQuery<InventoryResponse>({
    queryKey: ["cms-seo-inventory", locale, sourceType],
    placeholderData: (previousData) => previousData,
    queryFn: async () => {
      const params = new URLSearchParams({
        locale,
        sourceType,
      });
      const response = await authedFetch(
        `/api/cms/seo/inventory?${params.toString()}`,
      );
      if (!response.ok) {
        throw new Error("Failed to load SEO inventory");
      }
      return response.json();
    },
  });

  const redirectsQuery = useQuery<{ redirects: RouteRedirect[] }>({
    queryKey: ["cms-seo-redirects"],
    queryFn: async () => {
      const response = await authedFetch("/api/cms/seo/redirects");
      if (!response.ok) {
        throw new Error("Failed to load redirects");
      }
      return response.json();
    },
  });

  const rawEntries = useMemo(
    () => inventoryQuery.data?.entries ?? [],
    [inventoryQuery.data?.entries],
  );

  const hasLocalDraft = useCallback(
    (entry: InventoryEntry) =>
      Boolean(
        draftsByStorageId[buildDraftStorageId(entry.routeKey, entry.locale)],
      ),
    [draftsByStorageId],
  );

  const healthFilteredEntries = useMemo(
    () =>
      rawEntries.filter((entry) =>
        matchesSeoHealthFilter(entry.needsSeoScore, seoHealthFilter),
      ),
    [rawEntries, seoHealthFilter],
  );

  const draftEntryCount = useMemo(
    () => healthFilteredEntries.filter((entry) => hasLocalDraft(entry)).length,
    [hasLocalDraft, healthFilteredEntries],
  );

  const entries = useMemo(
    () =>
      draftVisibilityFilter === "drafts"
        ? healthFilteredEntries.filter((entry) => hasLocalDraft(entry))
        : healthFilteredEntries,
    [draftVisibilityFilter, hasLocalDraft, healthFilteredEntries],
  );

  const sourceTypeOptions = useMemo(() => {
    const values =
      sourceTypeCatalog.length > 0
        ? sourceTypeCatalog
        : Array.from(new Set(rawEntries.map((entry) => entry.sourceType))).sort(
            (a, b) => a.localeCompare(b),
          );
    return ["all", ...Array.from(values).sort((a, b) => a.localeCompare(b))];
  }, [rawEntries, sourceTypeCatalog]);

  const localeComboOptions = useMemo<ComboOption[]>(
    () => [
      {
        value: "en",
        label: "English",
        description: "Manage English SEO routes.",
      },
      {
        value: "ar",
        label: "Arabic",
        description: "Manage Arabic SEO routes.",
      },
    ],
    [],
  );

  const sourceTypeComboOptions = useMemo<ComboOption[]>(
    () =>
      sourceTypeOptions.map((option) => ({
        value: option,
        label: formatSourceTypeLabel(option),
        description:
          option === "all"
            ? "Include all route source types."
            : `Only ${formatSourceTypeLabel(option)} routes.`,
      })),
    [sourceTypeOptions],
  );

  const seoHealthComboOptions = useMemo<ComboOption[]>(
    () => [
      {
        value: "all",
        label: "All",
        description: "Show all pages regardless of SEO score.",
      },
      {
        value: "needs-attention",
        label: "Needs attention",
        description: "Show pages with higher SEO improvement priority.",
      },
      {
        value: "good",
        label: "Good",
        description: "Show pages with moderate SEO priority.",
      },
      {
        value: "excellent",
        label: "Excellent",
        description: "Show pages with low SEO priority.",
      },
    ],
    [],
  );

  useEffect(() => {
    const nextCatalog = inventoryQuery.data?.sourceTypes ?? [];
    if (nextCatalog.length === 0) {
      return;
    }

    const normalized = Array.from(new Set(nextCatalog)).sort((a, b) =>
      a.localeCompare(b),
    );
    setSourceTypeCatalog((prev) => {
      if (
        prev.length === normalized.length &&
        prev.every((value, index) => value === normalized[index])
      ) {
        return prev;
      }

      return normalized;
    });
  }, [inventoryQuery.data?.sourceTypes]);

  useEffect(() => {
    if (sourceTypeOptions.length <= 1) {
      return;
    }

    if (!sourceTypeOptions.includes(sourceType)) {
      setSourceType("all");
    }
  }, [sourceType, sourceTypeOptions]);

  useEffect(() => {
    if (
      selectedRouteKey &&
      !entries.some((entry) => entry.routeKey === selectedRouteKey)
    ) {
      setSelectedRouteKey("");
    }
  }, [entries, selectedRouteKey]);

  const selectedEntry = useMemo(
    () => entries.find((entry) => entry.routeKey === selectedRouteKey) ?? null,
    [entries, selectedRouteKey],
  );
  const selectedEntryDraft = selectedEntry
    ? (draftsByStorageId[
        buildDraftStorageId(selectedEntry.routeKey, selectedEntry.locale)
      ] ?? null)
    : null;

  const workspaceNoticeEntry = useMemo(() => {
    if (!workspaceDraftNotice) {
      return null;
    }

    return (
      rawEntries.find(
        (entry) =>
          entry.routeKey === workspaceDraftNotice.routeKey &&
          entry.locale === workspaceDraftNotice.locale,
      ) ?? null
    );
  }, [rawEntries, workspaceDraftNotice]);

  const sortedEntries = useMemo(
    () => [...entries].sort((a, b) => a.pathname.localeCompare(b.pathname)),
    [entries],
  );

  const pageOptions = useMemo<ComboOption[]>(
    () =>
      sortedEntries.map((entry) => {
        const health = getSeoHealthBadge(entry.needsSeoScore);
        const draft =
          draftsByStorageId[buildDraftStorageId(entry.routeKey, entry.locale)];
        return {
          value: entry.routeKey,
          label: entry.pathname,
          description: `${entry.sourceTitle ?? entry.label} • ${
            entry.sourceType
          } • ${health.label} ${entry.needsSeoScore}${
            draft ? ` • Draft ${formatDraftSavedRelative(draft.savedAt)}` : ""
          }`,
          badge: draft
            ? "Local draft"
            : `${health.label} • ${entry.needsSeoScore}`,
          badgeVariant: draft ? "secondary" : health.variant,
          searchTerms: [
            entry.label,
            entry.sourceDescription ?? "",
            entry.sourceType,
            draft ? "local draft" : "",
          ],
        };
      }),
    [draftsByStorageId, sortedEntries],
  );

  const summary = inventoryQuery.data?.summary ?? {
    total: 0,
    highPriority: 0,
    mediumPriority: 0,
    lowPriority: 0,
  };
  const selectedEntryHealth = selectedEntry
    ? getSeoHealthBadge(selectedEntry.needsSeoScore)
    : null;
  const activeEditorDraft = formState
    ? (draftsByStorageId[
        buildDraftStorageId(formState.routeKey, formState.locale)
      ] ?? null)
    : null;

  const hasActiveFilters =
    locale !== "en" ||
    sourceType !== "all" ||
    seoHealthFilter !== "all" ||
    draftVisibilityFilter !== "all" ||
    selectedRouteKey.length > 0;

  const clearFilters = () => {
    setLocale("en");
    setSourceType("all");
    setSeoHealthFilter("all");
    setDraftVisibilityFilter("all");
    setSelectedRouteKey("");
  };

  const openEditor = async (entry: InventoryEntry) => {
    const requestId = editorRequestRef.current + 1;
    editorRequestRef.current = requestId;
    setFormState(null);
    setEditorFeedback(null);
    setEditorLoading(true);
    setEditorOpen(true);

    try {
      const params = new URLSearchParams({
        locale: entry.locale,
        routeKey: entry.routeKey,
      });

      const response = await authedFetch(
        `/api/cms/seo/overrides?${params.toString()}`,
      );
      if (!response.ok) {
        throw new Error("Failed to load route override");
      }

      const payload = (await response.json()) as { overrides: SeoOverride[] };
      const existing = payload.overrides[0];

      const nextState = defaultFormState(
        entry.routeKey,
        entry.locale,
        buildAutogeneratedState(entry),
      );

      if (existing) {
        nextState.updatedAt = existing.updated_at;
        nextState.hasExistingOverride = true;
        nextState.title = existing.title ?? "";
        nextState.description = existing.description ?? "";
        nextState.canonicalUrl = existing.canonical_url ?? "";
        nextState.robotsIndex = existing.robots_index;
        nextState.robotsFollow = existing.robots_follow;
        nextState.ogTitle = existing.og_title ?? "";
        nextState.ogDescription = existing.og_description ?? "";
        nextState.ogImageUrl = existing.og_image_url ?? "";
        nextState.twitterTitle = existing.twitter_title ?? "";
        nextState.twitterDescription = existing.twitter_description ?? "";
        nextState.twitterImageUrl = existing.twitter_image_url ?? "";
        nextState.keywords = (existing.keywords ?? []).join(", ");
        nextState.aiSummary = existing.ai_summary ?? "";
        nextState.llmsInclude = existing.llms_include;
        nextState.llmsPriority = existing.llms_priority;
      }

      const draftStorageId = buildDraftStorageId(entry.routeKey, entry.locale);
      const savedDraft = draftsByStorageId[draftStorageId];
      const formWithDraft = savedDraft
        ? applyDraftToFormState(nextState, savedDraft)
        : nextState;

      if (requestId === editorRequestRef.current) {
        setFormState(formWithDraft);
        if (savedDraft) {
          const date = new Date(savedDraft.savedAt);
          const draftDateLabel = Number.isNaN(date.getTime())
            ? "a previous session"
            : date.toLocaleString();
          setEditorFeedback({
            tone: "info",
            message: `Loaded local draft from ${draftDateLabel}. Publish to apply changes.`,
          });
        }
      }
    } catch (error: any) {
      if (requestId !== editorRequestRef.current) {
        return;
      }
      toast({
        title: "Could not load SEO override",
        description: error?.message ?? "Try again.",
        variant: "destructive",
      });
      setQueuedPublishStorageId(null);
      setEditorOpen(false);
      setFormState(null);
    } finally {
      if (requestId === editorRequestRef.current) {
        setEditorLoading(false);
      }
    }
  };

  const saveDraft = ({
    closeEditor = false,
  }: { closeEditor?: boolean } = {}) => {
    if (!formState) {
      return;
    }

    const draftStorageId = buildDraftStorageId(
      formState.routeKey,
      formState.locale,
    );
    const drafts = readSeoOverrideDrafts();
    drafts[draftStorageId] = {
      ...toDraftSnapshot(formState),
      savedAt: new Date().toISOString(),
    };
    persistDrafts(drafts);

    setEditorFeedback({
      tone: "success",
      message: "Draft saved locally. Publish when you are ready to go live.",
    });
    toast({ title: "Draft saved" });

    if (closeEditor) {
      const savedDraft = drafts[draftStorageId];
      if (savedDraft) {
        setWorkspaceDraftNotice({
          routeKey: formState.routeKey,
          locale: formState.locale,
          savedAt: savedDraft.savedAt,
        });
      }
      setEditorOpen(false);
    }
  };

  const clearDraft = useCallback(
    (routeKey: string, localeValue: "en" | "ar") => {
      const draftStorageId = buildDraftStorageId(routeKey, localeValue);
      const drafts = { ...readSeoOverrideDrafts() };
      if (!drafts[draftStorageId]) {
        return;
      }

      delete drafts[draftStorageId];
      persistDrafts(drafts);
      setWorkspaceDraftNotice((prev) =>
        prev && prev.routeKey === routeKey && prev.locale === localeValue
          ? null
          : prev,
      );
    },
    [persistDrafts],
  );

  const saveOverride = useCallback(
    async ({ closeEditor = false }: { closeEditor?: boolean } = {}) => {
      if (!formState) return;

      setEditorSaving(true);

      try {
        const keywords = formState.keywords
          .split(",")
          .map((item) => item.trim())
          .filter(Boolean);

        const response = await authedFetch("/api/cms/seo/overrides", {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            routeKey: formState.routeKey,
            locale: formState.locale,
            updatedAt: formState.updatedAt,
            title: formState.title || null,
            description: formState.description || null,
            canonicalUrl: formState.canonicalUrl || null,
            robotsIndex: formState.robotsIndex,
            robotsFollow: formState.robotsFollow,
            ogTitle: formState.ogTitle || null,
            ogDescription: formState.ogDescription || null,
            ogImageUrl: formState.ogImageUrl || null,
            twitterTitle: formState.twitterTitle || null,
            twitterDescription: formState.twitterDescription || null,
            twitterImageUrl: formState.twitterImageUrl || null,
            keywords: keywords.length > 0 ? keywords : null,
            aiSummary: formState.aiSummary || null,
            llmsInclude: formState.llmsInclude,
            llmsPriority: formState.llmsPriority,
          }),
        });

        if (!response.ok) {
          const body = await response.json().catch(() => null);
          throw new Error(body?.error ?? "Failed to save SEO override");
        }

        toast({
          title: "SEO override published",
          description: `${formState.routeKey} has been updated.`,
        });
        setEditorFeedback({
          tone: "success",
          message:
            "Published successfully. Your override is now active for this page.",
        });
        clearDraft(formState.routeKey, formState.locale);
        setWorkspaceDraftNotice((prev) =>
          prev &&
          prev.routeKey === formState.routeKey &&
          prev.locale === formState.locale
            ? null
            : prev,
        );

        await inventoryQuery.refetch();
        if (closeEditor) {
          setEditorOpen(false);
        }
      } catch (error: any) {
        setEditorFeedback({
          tone: "error",
          message: error?.message ?? "Please try again.",
        });
        toast({
          title: "Publish failed",
          description: error?.message ?? "Please try again.",
          variant: "destructive",
        });
      } finally {
        setEditorSaving(false);
        setQueuedPublishStorageId(null);
      }
    },
    [clearDraft, formState, inventoryQuery, toast],
  );

  useEffect(() => {
    if (!queuedPublishStorageId || !formState || editorLoading) {
      return;
    }

    const currentStorageId = buildDraftStorageId(
      formState.routeKey,
      formState.locale,
    );
    if (currentStorageId !== queuedPublishStorageId) {
      return;
    }

    setQueuedPublishStorageId(null);
    void saveOverride({ closeEditor: true });
  }, [editorLoading, formState, queuedPublishStorageId, saveOverride]);

  const resetOverridesToAutogenerated = () => {
    setFormState((prev) => {
      if (!prev) {
        return prev;
      }

      return {
        ...prev,
        title: "",
        description: "",
        canonicalUrl: "",
        robotsIndex: prev.autogenerated.robotsIndex,
        robotsFollow: prev.autogenerated.robotsFollow,
        ogTitle: "",
        ogDescription: "",
        ogImageUrl: "",
        twitterTitle: "",
        twitterDescription: "",
        twitterImageUrl: "",
        keywords: "",
        aiSummary: "",
        llmsInclude: prev.autogenerated.llmsInclude,
        llmsPriority: prev.autogenerated.llmsPriority,
      };
    });
  };

  const createRedirect = async () => {
    const fromPath = normalizeRedirectPathInput(redirectFrom);
    const toPath = normalizeRedirectPathInput(redirectTo);

    if (!fromPath || !toPath) {
      toast({
        title: "Missing redirect paths",
        description: "Provide both from and to paths.",
        variant: "destructive",
      });
      return;
    }

    if (!isValidSitePath(fromPath) || !isValidSitePath(toPath)) {
      toast({
        title: "Invalid redirect path",
        description: "Redirect paths must be site-relative (for example /old).",
        variant: "destructive",
      });
      return;
    }

    if (fromPath === toPath) {
      toast({
        title: "Invalid redirect path",
        description: "Source and target paths cannot be identical.",
        variant: "destructive",
      });
      return;
    }

    setRedirectSaving(true);
    try {
      const response = await authedFetch("/api/cms/seo/redirects", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          fromPath,
          toPath,
          code: 301,
          isActive: true,
          source: "cms.seo.workspace",
        }),
      });

      if (!response.ok) {
        const body = await response.json().catch(() => null);
        throw new Error(body?.error ?? "Failed to create redirect");
      }

      setRedirectFrom("");
      setRedirectTo("");
      await redirectsQuery.refetch();
      toast({ title: "Redirect created" });
    } catch (error: any) {
      toast({
        title: "Failed to create redirect",
        description: error?.message ?? "Try again.",
        variant: "destructive",
      });
    } finally {
      setRedirectSaving(false);
    }
  };

  const toggleRedirect = async (entry: RouteRedirect) => {
    if (redirectToggleId) {
      return;
    }

    setRedirectToggleId(entry.id);
    try {
      const response = await authedFetch("/api/cms/seo/redirects", {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          id: entry.id,
          isActive: !entry.is_active,
        }),
      });

      if (!response.ok) {
        const body = await response.json().catch(() => null);
        throw new Error(body?.error ?? "Failed to update redirect");
      }

      await redirectsQuery.refetch();
    } catch (error: any) {
      toast({
        title: "Redirect update failed",
        description: error?.message ?? "Try again.",
        variant: "destructive",
      });
    } finally {
      setRedirectToggleId(null);
    }
  };

  return (
    <div className="space-y-8 pb-12">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between gap-4">
            <span>SEO Control Center</span>
            <Button
              variant="outline"
              size="sm"
              onClick={() => inventoryQuery.refetch()}
            >
              {inventoryQuery.isFetching ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <RefreshCcw className="mr-2 h-4 w-4" />
              )}
              Refresh
            </Button>
          </CardTitle>
          <CardDescription className="flex flex-wrap items-center gap-2">
            <span>Pick a page, edit SEO fields, then publish.</span>
            <Button
              variant="link"
              size="sm"
              className="h-auto p-0 text-sm"
              onClick={() => setHelpDialogOpen(true)}
            >
              <CircleHelp className="h-4 w-4" />
              How this works
            </Button>
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-3 md:grid-cols-4">
            <div className="space-y-2 md:col-span-2">
              <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Page to optimize
              </p>
              <ComboBox
                value={selectedRouteKey}
                options={pageOptions}
                placeholder="Choose a page (route or title)"
                searchPlaceholder="Search by route or title..."
                emptyLabel="No pages match the current filters."
                disabled={inventoryQuery.isLoading || entries.length === 0}
                onChange={setSelectedRouteKey}
                contentClassName="w-[min(720px,calc(100vw-3rem))] p-0"
              />
            </div>
            <div className="space-y-2">
              <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Language
              </p>
              <ComboBox
                value={locale}
                options={localeComboOptions}
                placeholder="Choose language"
                searchPlaceholder="Search language..."
                emptyLabel="No language found."
                onChange={(value) => {
                  if (value === "en" || value === "ar") {
                    setLocale(value);
                  }
                }}
                contentClassName="w-[min(340px,calc(100vw-3rem))] p-0"
              />
            </div>
            <div className="space-y-2">
              <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Source type
              </p>
              <ComboBox
                value={sourceType}
                options={sourceTypeComboOptions}
                placeholder="Choose source type"
                searchPlaceholder="Search source types..."
                emptyLabel="No source type found."
                onChange={setSourceType}
                contentClassName="w-[min(420px,calc(100vw-3rem))] p-0"
              />
            </div>
          </div>

          <div className="grid gap-3 md:grid-cols-[auto_auto_auto_1fr_auto] md:items-center">
            <Button
              variant={seoHealthFilter === "all" ? "secondary" : "outline"}
              size="sm"
              className="justify-start"
              onClick={() => setSeoHealthFilter("all")}
            >
              TOTAL: {summary.total}
            </Button>
            <Button
              variant={
                seoHealthFilter === "needs-attention"
                  ? "destructive"
                  : "outline"
              }
              size="sm"
              className="justify-start"
              onClick={() => setSeoHealthFilter("needs-attention")}
            >
              HIGH PRIORITY: {summary.highPriority}
            </Button>
            <Button
              variant={
                draftVisibilityFilter === "drafts" ? "secondary" : "outline"
              }
              size="sm"
              className="justify-start"
              onClick={() =>
                setDraftVisibilityFilter((prev) =>
                  prev === "drafts" ? "all" : "drafts",
                )
              }
            >
              LOCAL DRAFTS: {draftEntryCount}
            </Button>
            <p className="text-sm text-muted-foreground">
              Showing {entries.length} page{entries.length === 1 ? "" : "s"} in
              current filters
              {draftVisibilityFilter === "drafts" ? " (local drafts only)" : ""}
              .
            </p>
            <div className="flex flex-wrap items-center gap-2 md:justify-end">
              <span className="text-sm text-muted-foreground">SEO health</span>
              <ComboBox
                value={seoHealthFilter}
                options={seoHealthComboOptions}
                placeholder="Choose SEO health"
                searchPlaceholder="Search SEO health..."
                emptyLabel="No SEO health option found."
                onChange={(value) => {
                  if (
                    value === "all" ||
                    value === "needs-attention" ||
                    value === "good" ||
                    value === "excellent"
                  ) {
                    setSeoHealthFilter(value);
                  }
                }}
                className="w-44"
                contentClassName="w-[min(360px,calc(100vw-3rem))] p-0"
              />
              <Button
                variant="outline"
                size="sm"
                onClick={clearFilters}
                disabled={!hasActiveFilters}
              >
                Clear filters
              </Button>
            </div>
          </div>

          {workspaceDraftNotice ? (
            <div className="rounded-md border border-emerald-500/40 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-700">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="space-y-1">
                  <p className="font-medium">
                    Local draft saved for {workspaceDraftNotice.routeKey}
                  </p>
                  <p className="text-xs">
                    Saved{" "}
                    {formatDraftSavedRelative(workspaceDraftNotice.savedAt)} (
                    {formatDraftSavedAbsolute(workspaceDraftNotice.savedAt)}).
                  </p>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      if (workspaceNoticeEntry) {
                        void openEditor(workspaceNoticeEntry);
                      }
                    }}
                    disabled={!workspaceNoticeEntry}
                  >
                    Resume draft
                  </Button>
                  <Button
                    size="sm"
                    onClick={() => {
                      if (!workspaceNoticeEntry) {
                        return;
                      }
                      const storageId = buildDraftStorageId(
                        workspaceNoticeEntry.routeKey,
                        workspaceNoticeEntry.locale,
                      );
                      setQueuedPublishStorageId(storageId);
                      void openEditor(workspaceNoticeEntry);
                    }}
                    disabled={!workspaceNoticeEntry}
                  >
                    Publish
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setWorkspaceDraftNotice(null)}
                  >
                    Dismiss
                  </Button>
                </div>
              </div>
            </div>
          ) : null}

          {inventoryQuery.isLoading ? (
            <div className="flex items-center gap-2 text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" /> Loading inventory...
            </div>
          ) : null}

          {inventoryQuery.isError ? (
            <div className="rounded-md border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">
              Could not load SEO inventory. Please refresh and try again.
            </div>
          ) : null}

          {!inventoryQuery.isLoading &&
          !inventoryQuery.isError &&
          entries.length === 0 ? (
            <div className="rounded-lg border border-dashed border-border/70 p-8 text-center text-muted-foreground">
              {draftVisibilityFilter === "drafts"
                ? "No local drafts in the current filters."
                : "No routes match current filters."}
            </div>
          ) : null}

          {!inventoryQuery.isLoading &&
          !inventoryQuery.isError &&
          entries.length > 0 &&
          !selectedEntry ? (
            <div className="rounded-lg border border-dashed border-border/70 bg-muted/10 p-4">
              <p className="text-sm font-medium text-foreground">Start here</p>
              <ol className="mt-2 space-y-1 text-sm text-muted-foreground">
                <li>1. Choose language and source type filters.</li>
                <li>2. Pick a page in &quot;Page to optimize&quot;.</li>
                <li>3. Click &quot;Edit SEO&quot; to open the editor.</li>
                <li>4. Save draft or publish your changes.</li>
              </ol>
            </div>
          ) : null}

          {selectedEntry ? (
            <div className="rounded-lg border border-border/70 p-4">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="space-y-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge variant="outline">{selectedEntry.sourceType}</Badge>
                    {selectedEntryDraft ? (
                      <Badge variant="secondary">Local draft</Badge>
                    ) : null}
                    {selectedEntryHealth ? (
                      <Badge variant={selectedEntryHealth.variant}>
                        {selectedEntryHealth.label}
                      </Badge>
                    ) : null}
                    <Badge variant="secondary">
                      score {selectedEntry.needsSeoScore}
                    </Badge>
                  </div>
                  <p className="font-medium text-foreground">
                    {selectedEntry.pathname}
                  </p>
                  {selectedEntryDraft ? (
                    <p className="text-xs text-muted-foreground">
                      Local draft saved{" "}
                      {formatDraftSavedRelative(selectedEntryDraft.savedAt)} (
                      {formatDraftSavedAbsolute(selectedEntryDraft.savedAt)}).
                    </p>
                  ) : null}
                  <p className="text-sm text-muted-foreground">
                    {selectedEntry.sourceTitle ?? selectedEntry.label}
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="outline" asChild>
                    <Link href={selectedEntry.pathname} target="_blank">
                      Preview
                    </Link>
                  </Button>
                  <Button
                    size="sm"
                    onClick={() => openEditor(selectedEntry)}
                    disabled={editorLoading}
                  >
                    Edit SEO
                  </Button>
                </div>
              </div>
            </div>
          ) : null}

          {!inventoryQuery.isLoading &&
          !inventoryQuery.isError &&
          entries.length > 0 ? (
            <div className="rounded-lg border border-border/70 p-4">
              <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
                <p className="text-sm font-medium text-foreground">
                  Filtered pages
                </p>
                <p className="text-xs text-muted-foreground">
                  Select any row to sync the page combobox.
                </p>
              </div>
              <div className="max-h-[420px] space-y-2 overflow-y-auto pr-1">
                {sortedEntries.map((entry) => {
                  const health = getSeoHealthBadge(entry.needsSeoScore);
                  const draft =
                    draftsByStorageId[
                      buildDraftStorageId(entry.routeKey, entry.locale)
                    ] ?? null;
                  const isSelected = selectedRouteKey === entry.routeKey;

                  return (
                    <div
                      key={`${entry.routeKey}-${entry.locale}`}
                      role="button"
                      tabIndex={0}
                      aria-pressed={isSelected}
                      onClick={() => setSelectedRouteKey(entry.routeKey)}
                      onKeyDown={(event) => {
                        if (event.key === "Enter" || event.key === " ") {
                          event.preventDefault();
                          setSelectedRouteKey(entry.routeKey);
                        }
                      }}
                      className={`rounded-md border p-3 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 focus-visible:ring-offset-2 ${
                        isSelected
                          ? "border-primary/50 bg-primary/5"
                          : "border-border/60 bg-background hover:border-primary/30 hover:bg-muted/20"
                      }`}
                    >
                      <div className="flex flex-wrap items-start justify-between gap-3">
                        <div className="space-y-1">
                          <div className="flex flex-wrap items-center gap-2">
                            <Badge variant="outline">{entry.sourceType}</Badge>
                            {draft ? (
                              <Badge variant="secondary">Local draft</Badge>
                            ) : null}
                            <Badge variant={health.variant}>
                              {health.label}
                            </Badge>
                            <Badge variant="secondary">
                              score {entry.needsSeoScore}
                            </Badge>
                            {isSelected ? (
                              <Badge variant="outline">Selected</Badge>
                            ) : null}
                          </div>
                          <p className="font-medium text-foreground">
                            {entry.pathname}
                          </p>
                          {draft ? (
                            <p className="text-xs text-muted-foreground">
                              Draft saved{" "}
                              {formatDraftSavedRelative(draft.savedAt)}
                            </p>
                          ) : null}
                          <p className="text-sm text-muted-foreground">
                            {entry.sourceTitle ?? entry.label}
                          </p>
                        </div>

                        <div
                          className="flex flex-wrap items-center gap-2"
                          onClick={(event) => event.stopPropagation()}
                          onKeyDown={(event) => event.stopPropagation()}
                        >
                          <Button size="sm" variant="outline" asChild>
                            <Link href={entry.pathname} target="_blank">
                              Preview
                            </Link>
                          </Button>
                          <Button
                            size="sm"
                            onClick={() => openEditor(entry)}
                            disabled={editorLoading}
                          >
                            Edit SEO
                          </Button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          ) : null}
        </CardContent>
      </Card>

      <Dialog open={helpDialogOpen} onOpenChange={setHelpDialogOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>How SEO Control Center works</DialogTitle>
          </DialogHeader>
          <div className="space-y-3 text-sm text-muted-foreground">
            <p>Use this flow to update SEO safely:</p>
            <ol className="space-y-1">
              <li>1. Set language and source filters.</li>
              <li>2. Select one page from the combobox.</li>
              <li>3. Open the editor to change SEO override fields.</li>
              <li>4. Save draft locally or publish to make updates live.</li>
            </ol>
          </div>
        </DialogContent>
      </Dialog>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <LinkIcon className="h-5 w-5" /> Redirect Continuity
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]">
            <Input
              value={redirectFrom}
              onChange={(event) => setRedirectFrom(event.target.value)}
              placeholder="From path (e.g. /old-slug)"
            />
            <Input
              value={redirectTo}
              onChange={(event) => setRedirectTo(event.target.value)}
              placeholder="To path (e.g. /new-slug)"
            />
            <Button onClick={createRedirect} disabled={redirectSaving}>
              {redirectSaving ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                "Create 301"
              )}
            </Button>
          </div>

          {redirectsQuery.isError ? (
            <div className="rounded-md border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">
              Could not load redirects. Please refresh and try again.
            </div>
          ) : null}

          <div className="space-y-2">
            {(redirectsQuery.data?.redirects ?? []).map((entry) => (
              <div
                key={entry.id}
                className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border/60 p-3"
              >
                <div className="space-y-1 text-sm">
                  <div className="font-medium">
                    {entry.from_path}{" "}
                    <span className="text-muted-foreground">→</span>{" "}
                    {entry.to_path}
                  </div>
                  <div className="text-muted-foreground">
                    {entry.code} • {entry.source ?? "n/a"}
                  </div>
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => toggleRedirect(entry)}
                  disabled={redirectToggleId === entry.id}
                >
                  {redirectToggleId === entry.id ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : entry.is_active ? (
                    "Disable"
                  ) : (
                    "Enable"
                  )}
                </Button>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <Dialog
        open={editorOpen}
        onOpenChange={(open) => {
          setEditorOpen(open);
          if (!open) {
            editorRequestRef.current += 1;
            setEditorLoading(false);
            setEditorFeedback(null);
            setQueuedPublishStorageId(null);
            setFormState(null);
          }
        }}
      >
        <DialogContent className="max-h-[95vh] overflow-y-auto sm:max-w-5xl">
          <DialogHeader>
            <DialogTitle>Edit SEO Override</DialogTitle>
          </DialogHeader>

          {editorLoading || !formState ? (
            <div className="flex items-center gap-2 text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" /> Loading override...
            </div>
          ) : (
            <div className="space-y-5">
              <div className="space-y-2 rounded-md border border-border/70 bg-muted/20 p-3 text-sm">
                <div>
                  Route:{" "}
                  <span className="font-medium">{formState.routeKey}</span>
                </div>
                {activeEditorDraft ? (
                  <p className="text-sm text-muted-foreground">
                    Editing local draft from{" "}
                    {formatDraftSavedAbsolute(activeEditorDraft.savedAt)} (
                    {formatDraftSavedRelative(activeEditorDraft.savedAt)}).
                  </p>
                ) : null}
                <p className="text-sm text-muted-foreground">
                  {formState.hasExistingOverride
                    ? "Existing override values are loaded into inputs."
                    : "No saved override yet. Empty inputs will keep autogenerated values."}
                </p>
              </div>

              <div className="rounded-md border border-blue-200/70 bg-blue-50/30 p-3 text-sm text-muted-foreground">
                Autogenerated baseline is shown under each field. Only input
                values are saved as overrides.
              </div>

              {editorFeedback ? (
                <div
                  className={`rounded-md border px-3 py-2 text-sm ${
                    editorFeedback.tone === "error"
                      ? "border-destructive/40 bg-destructive/10 text-destructive"
                      : editorFeedback.tone === "success"
                        ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-700"
                        : "border-blue-500/40 bg-blue-500/10 text-blue-700"
                  }`}
                >
                  {editorFeedback.message}
                </div>
              ) : null}

              <div className="grid gap-4 lg:grid-cols-2">
                <div className="min-w-0 space-y-2">
                  <Label>SEO title</Label>
                  <Input
                    value={formState.title}
                    onChange={(event) =>
                      setFormState((prev) =>
                        prev ? { ...prev, title: event.target.value } : prev,
                      )
                    }
                    placeholder="Override SEO title"
                  />
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formatAutogeneratedValue(formState.autogenerated.title)}
                    </p>
                    <FieldStatusBadge
                      overridden={hasTextOverride(formState.title)}
                    />
                  </div>
                </div>
                <div className="min-w-0 space-y-2">
                  <Label>Canonical URL/path</Label>
                  <Input
                    value={formState.canonicalUrl}
                    onChange={(event) =>
                      setFormState((prev) =>
                        prev
                          ? { ...prev, canonicalUrl: event.target.value }
                          : prev,
                      )
                    }
                    placeholder="Override canonical URL/path"
                  />
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formatAutogeneratedValue(
                        formState.autogenerated.canonicalUrl,
                      )}
                    </p>
                    <FieldStatusBadge
                      overridden={hasTextOverride(formState.canonicalUrl)}
                    />
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <Label>Meta description</Label>
                <Textarea
                  value={formState.description}
                  onChange={(event) =>
                    setFormState((prev) =>
                      prev
                        ? { ...prev, description: event.target.value }
                        : prev,
                    )
                  }
                  placeholder="Override meta description"
                />
                <div className="flex flex-col gap-1">
                  <p className={AUTOGENERATED_VALUE_CLASS}>
                    Autogenerated:{" "}
                    {formatAutogeneratedValue(
                      formState.autogenerated.description,
                    )}
                  </p>
                  <FieldStatusBadge
                    overridden={hasTextOverride(formState.description)}
                  />
                </div>
              </div>

              <div className="grid gap-4 lg:grid-cols-2">
                <div className="min-w-0 space-y-2">
                  <Label>OpenGraph title</Label>
                  <Input
                    value={formState.ogTitle}
                    onChange={(event) =>
                      setFormState((prev) =>
                        prev ? { ...prev, ogTitle: event.target.value } : prev,
                      )
                    }
                    placeholder="Override OpenGraph title"
                  />
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formatAutogeneratedValue(
                        formState.autogenerated.ogTitle,
                      )}
                    </p>
                    <FieldStatusBadge
                      overridden={hasTextOverride(formState.ogTitle)}
                    />
                  </div>
                </div>
                <div className="min-w-0 space-y-2">
                  <Label>OpenGraph image URL</Label>
                  <Input
                    value={formState.ogImageUrl}
                    onChange={(event) =>
                      setFormState((prev) =>
                        prev
                          ? { ...prev, ogImageUrl: event.target.value }
                          : prev,
                      )
                    }
                    placeholder="Override OpenGraph image URL"
                  />
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formatAutogeneratedValue(
                        formState.autogenerated.ogImageUrl,
                      )}
                    </p>
                    <FieldStatusBadge
                      overridden={hasTextOverride(formState.ogImageUrl)}
                    />
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <Label>OpenGraph description</Label>
                <Textarea
                  value={formState.ogDescription}
                  onChange={(event) =>
                    setFormState((prev) =>
                      prev
                        ? { ...prev, ogDescription: event.target.value }
                        : prev,
                    )
                  }
                  placeholder="Override OpenGraph description"
                />
                <div className="flex flex-col gap-1">
                  <p className={AUTOGENERATED_VALUE_CLASS}>
                    Autogenerated:{" "}
                    {formatAutogeneratedValue(
                      formState.autogenerated.ogDescription,
                    )}
                  </p>
                  <FieldStatusBadge
                    overridden={hasTextOverride(formState.ogDescription)}
                  />
                </div>
              </div>

              <div className="grid gap-4 lg:grid-cols-2">
                <div className="min-w-0 space-y-2">
                  <Label>Twitter title</Label>
                  <Input
                    value={formState.twitterTitle}
                    onChange={(event) =>
                      setFormState((prev) =>
                        prev
                          ? { ...prev, twitterTitle: event.target.value }
                          : prev,
                      )
                    }
                    placeholder="Override Twitter title"
                  />
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formatAutogeneratedValue(
                        formState.autogenerated.twitterTitle,
                      )}
                    </p>
                    <FieldStatusBadge
                      overridden={hasTextOverride(formState.twitterTitle)}
                    />
                  </div>
                </div>
                <div className="min-w-0 space-y-2">
                  <Label>Twitter image URL</Label>
                  <Input
                    value={formState.twitterImageUrl}
                    onChange={(event) =>
                      setFormState((prev) =>
                        prev
                          ? { ...prev, twitterImageUrl: event.target.value }
                          : prev,
                      )
                    }
                    placeholder="Override Twitter image URL"
                  />
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formatAutogeneratedValue(
                        formState.autogenerated.twitterImageUrl,
                      )}
                    </p>
                    <FieldStatusBadge
                      overridden={hasTextOverride(formState.twitterImageUrl)}
                    />
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <Label>Twitter description</Label>
                <Textarea
                  value={formState.twitterDescription}
                  onChange={(event) =>
                    setFormState((prev) =>
                      prev
                        ? { ...prev, twitterDescription: event.target.value }
                        : prev,
                    )
                  }
                  placeholder="Override Twitter description"
                />
                <div className="flex flex-col gap-1">
                  <p className={AUTOGENERATED_VALUE_CLASS}>
                    Autogenerated:{" "}
                    {formatAutogeneratedValue(
                      formState.autogenerated.twitterDescription,
                    )}
                  </p>
                  <FieldStatusBadge
                    overridden={hasTextOverride(formState.twitterDescription)}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Keywords (comma separated)</Label>
                <Input
                  value={formState.keywords}
                  onChange={(event) =>
                    setFormState((prev) =>
                      prev ? { ...prev, keywords: event.target.value } : prev,
                    )
                  }
                  placeholder="Override keywords"
                />
                <div className="flex flex-col gap-1">
                  <p className={AUTOGENERATED_VALUE_CLASS}>
                    Autogenerated:{" "}
                    {formatAutogeneratedValue(formState.autogenerated.keywords)}
                  </p>
                  <FieldStatusBadge
                    overridden={hasTextOverride(formState.keywords)}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label>AI summary for llms.txt</Label>
                <Textarea
                  value={formState.aiSummary}
                  onChange={(event) =>
                    setFormState((prev) =>
                      prev ? { ...prev, aiSummary: event.target.value } : prev,
                    )
                  }
                  placeholder="Override AI summary for llms.txt"
                />
                <div className="flex flex-col gap-1">
                  <p className={AUTOGENERATED_VALUE_CLASS}>
                    Autogenerated:{" "}
                    {formatAutogeneratedValue(
                      formState.autogenerated.aiSummary,
                    )}
                  </p>
                  <FieldStatusBadge
                    overridden={hasTextOverride(formState.aiSummary)}
                  />
                </div>
              </div>

              <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                <div className="min-w-0 space-y-2">
                  <Label>Robots: indexing</Label>
                  <Select
                    value={formState.robotsIndex ? "index" : "noindex"}
                    onValueChange={(value) =>
                      setFormState((prev) =>
                        prev
                          ? { ...prev, robotsIndex: value === "index" }
                          : prev,
                      )
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Choose indexing" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="index">Index</SelectItem>
                      <SelectItem value="noindex">Noindex</SelectItem>
                    </SelectContent>
                  </Select>
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formState.autogenerated.robotsIndex
                        ? "Index"
                        : "Noindex"}
                    </p>
                    <FieldStatusBadge
                      overridden={
                        formState.robotsIndex !==
                        formState.autogenerated.robotsIndex
                      }
                    />
                  </div>
                </div>

                <div className="min-w-0 space-y-2">
                  <Label>Robots: follow links</Label>
                  <Select
                    value={formState.robotsFollow ? "follow" : "nofollow"}
                    onValueChange={(value) =>
                      setFormState((prev) =>
                        prev
                          ? { ...prev, robotsFollow: value === "follow" }
                          : prev,
                      )
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Choose follow rule" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="follow">Follow</SelectItem>
                      <SelectItem value="nofollow">Nofollow</SelectItem>
                    </SelectContent>
                  </Select>
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formState.autogenerated.robotsFollow
                        ? "Follow"
                        : "Nofollow"}
                    </p>
                    <FieldStatusBadge
                      overridden={
                        formState.robotsFollow !==
                        formState.autogenerated.robotsFollow
                      }
                    />
                  </div>
                </div>

                <div className="min-w-0 space-y-2">
                  <Label>LLMS inclusion</Label>
                  <Select
                    value={formState.llmsInclude ? "include" : "exclude"}
                    onValueChange={(value) =>
                      setFormState((prev) =>
                        prev
                          ? { ...prev, llmsInclude: value === "include" }
                          : prev,
                      )
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Choose inclusion rule" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="include">
                        Include in llms.txt
                      </SelectItem>
                      <SelectItem value="exclude">
                        Exclude from llms.txt
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated:{" "}
                      {formState.autogenerated.llmsInclude
                        ? "Include"
                        : "Exclude"}
                    </p>
                    <FieldStatusBadge
                      overridden={
                        formState.llmsInclude !==
                        formState.autogenerated.llmsInclude
                      }
                    />
                  </div>
                </div>

                <div className="min-w-0 space-y-2">
                  <Label>LLMS priority</Label>
                  <Input
                    type="number"
                    value={formState.llmsPriority}
                    onChange={(event) =>
                      setFormState((prev) =>
                        prev
                          ? (() => {
                              const raw = event.target.value;
                              if (raw.trim().length === 0) {
                                return { ...prev, llmsPriority: 0 };
                              }
                              const parsed = Number(raw);
                              if (!Number.isFinite(parsed)) {
                                return prev;
                              }

                              return {
                                ...prev,
                                llmsPriority: clampLlmsPriority(parsed),
                              };
                            })()
                          : prev,
                      )
                    }
                    placeholder="Override LLMS priority"
                  />
                  <div className="flex flex-col gap-1">
                    <p className={AUTOGENERATED_VALUE_CLASS}>
                      Autogenerated: {formState.autogenerated.llmsPriority}
                    </p>
                    <FieldStatusBadge
                      overridden={
                        formState.llmsPriority !==
                        formState.autogenerated.llmsPriority
                      }
                    />
                  </div>
                </div>
              </div>

              <div className="rounded-md border border-border/70 bg-muted/10 p-3 text-sm">
                <p className="mb-2 font-medium">Effective preview</p>
                <div className="grid gap-2 text-sm text-muted-foreground xl:grid-cols-2 [&>p]:break-words">
                  <p>
                    Title:{" "}
                    {formatAutogeneratedValue(
                      toEffectiveValue(
                        formState.title,
                        formState.autogenerated.title,
                      ),
                    )}
                  </p>
                  <p>
                    Canonical:{" "}
                    {formatAutogeneratedValue(
                      toEffectiveValue(
                        formState.canonicalUrl,
                        formState.autogenerated.canonicalUrl,
                      ),
                    )}
                  </p>
                  <p>
                    Description:{" "}
                    {formatAutogeneratedValue(
                      toEffectiveValue(
                        formState.description,
                        formState.autogenerated.description,
                      ),
                    )}
                  </p>
                  <p>
                    OpenGraph title:{" "}
                    {formatAutogeneratedValue(
                      toEffectiveValue(
                        formState.ogTitle,
                        formState.autogenerated.ogTitle,
                      ),
                    )}
                  </p>
                  <p>
                    OpenGraph image:{" "}
                    {formatAutogeneratedValue(
                      toEffectiveValue(
                        formState.ogImageUrl,
                        formState.autogenerated.ogImageUrl,
                      ),
                    )}
                  </p>
                  <p>
                    Twitter title:{" "}
                    {formatAutogeneratedValue(
                      toEffectiveValue(
                        formState.twitterTitle,
                        formState.autogenerated.twitterTitle,
                      ),
                    )}
                  </p>
                  <p>
                    Twitter image:{" "}
                    {formatAutogeneratedValue(
                      toEffectiveValue(
                        formState.twitterImageUrl,
                        formState.autogenerated.twitterImageUrl,
                      ),
                    )}
                  </p>
                  <p>
                    AI summary:{" "}
                    {formatAutogeneratedValue(
                      toEffectiveValue(
                        formState.aiSummary,
                        formState.autogenerated.aiSummary,
                      ),
                    )}
                  </p>
                  <p>
                    Robots: {formState.robotsIndex ? "index" : "noindex"},{" "}
                    {formState.robotsFollow ? "follow" : "nofollow"}
                  </p>
                  <p>
                    llms.txt: {formState.llmsInclude ? "include" : "exclude"}{" "}
                    (priority {formState.llmsPriority})
                  </p>
                </div>
              </div>

              <div className="mt-2 flex flex-col gap-2 border-t border-border/70 pt-3 sm:flex-row sm:items-center sm:justify-between">
                <Button
                  variant="ghost"
                  onClick={resetOverridesToAutogenerated}
                  disabled={editorSaving}
                >
                  Reset to autogenerated
                </Button>
                <div className="flex flex-wrap gap-2 sm:justify-end">
                  <Button
                    variant="outline"
                    onClick={() => setEditorOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => saveDraft({ closeEditor: true })}
                    disabled={editorSaving}
                  >
                    Save draft & close
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => saveDraft()}
                    disabled={editorSaving}
                  >
                    Save draft
                  </Button>
                  <Button
                    onClick={() => saveOverride()}
                    disabled={editorSaving}
                  >
                    {editorSaving ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : null}
                    Publish
                  </Button>
                </div>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
